name: Deploy Staging to Live site

on:
  workflow_dispatch:
  push:
    paths:
      - site/**
    branches:
      - live

env:
  USER_TOKEN: ${{ secrets.PROD_TOKEN }}
  USER_NAME: "Chineham Repair Cafe Site (GitHub Actions)"
  USER_EMAIL: "chineham-repair-cafe@users.noreply.github.com"
  OWNER: chineham-repair-cafe
  REPOSITORY_NAME: chineham-site-live

jobs:
  push-staging-to-live:
    name: Push to live website, when ready.
    if: ${{ github.repository == 'chineham-repair-cafe/chineham-site-staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add Wiki as a remote
        run: git remote add live-repo https://$OWNER:$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.git

      - name: Make sure to fetch remotes, unshallowed
        run: git fetch --unshallow origin

      - name: Mirror all commits to live Wiki remote.
        run: git push --force live-repo live:live
